import fs from 'fs';

let appCode = fs.readFileSync('frontend/App.jsx', 'utf8');

appCode = appCode.replace(
  'import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";\nimport React, { useEffect, useRef, useState } from "react";\nimport { BrowserRouter, Routes, Route, Navigate, useLocation, } from "react-router-dom";\nimport { QueryClient, QueryClientProvider, useQuery } from "@tanstack/react-query";\nimport { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";\nimport React, { useEffect, useRef, useState } from "react";\nimport { BrowserRouter, Routes, Route, Navigate, useLocation, } from "react-router-dom";\nimport { QueryClient, QueryClientProvider, useQuery } from "@tanstack/react-query";\nimport { ErrorBoundary } from "./components/ui/ErrorBoundary";\nimport { Sidebar } from "./components/layout/Sidebar";\nimport { RightSidebar } from "./components/layout/RightSidebar";\nimport { TopNav } from "./components/layout/TopNav";\nimport { MobileNav } from "./components/layout/MobileNav";\nimport { Dashboard } from "./pages/Dashboard";\nimport { Konnect } from "./pages/Konnect";\nimport { Landing } from "./pages/Landing";\nimport { Profile } from "./pages/Profile";\nimport { PostDetail } from "./pages/PostDetail";',
  'import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";\nimport React, { useEffect, useRef, useState } from "react";\nimport { BrowserRouter, Routes, Route, Navigate, useLocation, } from "react-router-dom";\nimport { QueryClient, QueryClientProvider, useQuery } from "@tanstack/react-query";\nimport { ErrorBoundary } from "./components/ui/ErrorBoundary";\nimport { Sidebar } from "./components/layout/Sidebar";\nimport { RightSidebar } from "./components/layout/RightSidebar";\nimport { TopNav } from "./components/layout/TopNav";\nimport { MobileNav } from "./components/layout/MobileNav";\nimport { Dashboard } from "./pages/Dashboard";\nimport { Konnect } from "./pages/Konnect";\nimport { Landing } from "./pages/Landing";\nimport { Teaky } from "./pages/Teaky";\nimport { Login } from "./pages/Login";\nimport { ForgotPassword } from "./pages/ForgotPassword";\nimport { ResetPassword } from "./pages/ResetPassword";\nimport { Groups } from "./pages/Groups";\nimport { Messages } from "./pages/Messages";\nimport { Profile } from "./pages/Profile";\nimport { PostDetail } from "./pages/PostDetail";'
);

fs.writeFileSync('frontend/App.jsx', appCode);
console.log('Fixed imports in App.jsx');
